---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Lint Code Base
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Check broken links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
  check-super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Check super-linter
        uses: github/super-linter@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          KUBERNETES_KUBECONFORM_OPTIONS: '-skip kind.x-k8s.io/v1alpha4/Cluster'
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_RUST_CLIPPY: false
  check-tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Install tox
        run: pip install tox
      - name: Run tox validation
        run: tox -e lint
