---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Scheduled Versions verification
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
permissions: read-all
jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          # Fine-grained PAT with contents:write and workflows:write scopes
          token: ${{ secrets.WORKFLOW_TOKEN }}
          persist-credentials: true
      - uses: technote-space/create-pr-action@91114507cf92349bec0a9a501c2edf1635427bc5 # 2.1.4
        with:
          EXECUTE_COMMANDS: |
            ./ci/update_versions.sh
          COMMIT_MESSAGE: "Upgrade versions files"
          COMMIT_NAME: "electrocucaracha bot"
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: "chore: update versions"
